// Hash values in this file are generated by Scripts/generate_hashes.py.
// Run that script when adding or removing elements/attributes.

// MARK: - FNV-1a hash functions

/// FNV-1a hash over a byte range, lowercasing ASCII letters.
/// Used for case-insensitive element/attribute lookups without String allocation.
@inline(__always)
func fnvHashLowered(_ bytes: UnsafeBufferPointer<UInt8>, _ start: Int, _ end: Int) -> UInt64 {
  var h: UInt64 = 14_695_981_039_346_656_037
  for i in start ..< end {
    var b = bytes[i]
    if b >= 0x41 && b <= 0x5A { b = b | 0x20 }
    h ^= UInt64(b)
    h &*= 1_099_511_628_211
  }
  return h
}

/// FNV-1a hash over a byte range, case-sensitive.
/// Used for preserveWhitespace lookups where only exact lowercase tag names match.
@inline(__always)
func fnvHash(_ bytes: UnsafeBufferPointer<UInt8>, _ start: Int, _ end: Int) -> UInt64 {
  var h: UInt64 = 14_695_981_039_346_656_037
  for i in start ..< end {
    h ^= UInt64(bytes[i])
    h &*= 1_099_511_628_211
  }
  return h
}

// MARK: - Named tag/attribute hashes

let scriptHash: UInt64 = 12_464_980_982_266_880_842
let styleHash: UInt64 = 13_795_232_291_291_665_398
let linkHash: UInt64 = 13_784_282_253_595_985_929
let aHash: UInt64 = 12_638_187_200_555_641_996
let svgHash: UInt64 = 9_396_663_974_420_250_913
let mathHash: UInt64 = 2_256_134_787_772_167_695
let typeHash: UInt64 = 12_075_340_201_627_130_925
let languageHash: UInt64 = 15_203_366_365_119_026_011
let charsetHash: UInt64 = 9_961_587_957_729_687_531
let srcHash: UInt64 = 9_392_701_334_512_935_369
let nameHash: UInt64 = 14_176_396_743_819_860_870
let idHash: UInt64 = 628_021_283_683_842_752
let draggableHash: UInt64 = 3_312_292_798_893_085_268
let valueAttrHash: UInt64 = 8_999_596_768_310_594_794
let styleAttrHash: UInt64 = 13_795_232_291_291_665_398

// MARK: - Hash-based element/attribute sets

/// HTML void elements — self-closing by definition, no closing tag needed.
let voidElementHashes: Set<UInt64> = [
  9_894_459_526_856_489_156, // area
  11_132_020_437_646_885_496, // base
  623_262_597_357_891_669, // br
  17_727_561_322_155_042_705, // col
  796_654_122_392_472_174, // embed
  628_892_096_893_196_639, // hr
  3_142_648_431_874_569_604, // img
  2_214_555_572_463_777_371, // input
  13_784_282_253_595_985_929, // link
  4_837_122_885_601_373_240, // meta
  869_638_551_241_974_738, // param
  8_564_681_157_369_146_808, // source
  16_052_404_288_867_766_460, // track
  6_819_565_948_730_898_986, // wbr
]

/// Elements whose content is not HTML — passed through without parsing.
let rawContentElementHashes: Set<UInt64> = [
  12_464_980_982_266_880_842, // script
  13_795_232_291_291_665_398, // style
]

/// Elements whose content whitespace must be preserved exactly as authored.
/// Case-SENSITIVE hashes (only lowercase tag names match).
let preserveWhitespaceHashes: Set<UInt64> = [
  8_646_156_028_890_705_350, // pre
  16_973_714_742_696_204_443, // textarea
]

/// Simple boolean attributes that always have their value collapsed.
/// `<input disabled="disabled">` → `<input disabled>`
/// Does NOT include `draggable` (enumerated) or `crossorigin`/`contenteditable` (empty-collapsible).
let booleanAttributeHashes: Set<UInt64> = [
  17_371_440_559_097_631_735, // allowfullscreen
  8_244_113_706_180_130_863, // async
  13_295_878_867_807_385_434, // autofocus
  3_132_881_932_252_203_336, // autoplay
  11_537_471_423_366_477_414, // checked
  6_270_155_962_352_560_262, // compact
  15_321_269_636_683_178_455, // controls
  5_872_319_017_975_890_277, // declare
  16_982_411_286_042_166_782, // default
  15_388_595_069_153_590_447, // defaultchecked
  3_404_849_431_112_222_849, // defaultmuted
  6_127_959_737_237_819_847, // defaultselected
  18_093_980_567_233_218_619, // defer
  1_126_807_131_552_367_653, // disabled
  8_131_395_913_820_547_230, // enabled
  9_864_818_412_069_420_778, // formnovalidate
  11_529_431_508_713_810_105, // hidden
  1_181_762_182_826_318_040, // indeterminate
  10_264_762_997_190_170_727, // inert
  13_226_746_628_050_902_145, // ismap
  6_673_961_055_171_169_762, // itemscope
  14_838_486_305_852_456_427, // loop
  5_360_854_783_551_888_097, // multiple
  15_424_629_985_205_250_928, // muted
  2_162_075_684_808_052_983, // nohref
  12_994_276_978_864_817_150, // noresize
  6_634_619_227_211_395_987, // noshade
  1_865_807_981_824_940_468, // novalidate
  49_427_684_717_134_366, // nowrap
  17_892_686_645_580_689_641, // open
  1_828_595_695_455_021_896, // pauseonexit
  11_389_206_710_689_427_095, // readonly
  4_160_101_248_123_522_816, // required
  9_922_039_119_802_503_859, // reversed
  17_244_590_884_182_342_621, // scoped
  11_305_414_455_751_680_614, // seamless
  271_429_125_968_069_076, // selected
  7_759_135_550_754_861_553, // sortable
  4_344_570_164_592_415_680, // truespeed
  14_099_250_715_444_918_689, // typemustmatch
  17_257_192_937_063_639_073, // visible
]

/// Attributes that are collapsed only when their value is empty.
/// `<div contenteditable="">` → `<div contenteditable>`
let emptyCollapsibleAttributeHashes: Set<UInt64> = [
  13_243_003_948_996_387_653, // crossorigin
  3_835_859_576_960_478_530, // contenteditable
]

/// Attributes that are safe to remove when their value is empty or all-whitespace.
/// Does NOT include src, alt, action, etc. which are semantically meaningful even when empty.
let emptyRemovableAttributeHashes: Set<UInt64> = [
  15_066_323_702_654_938_015, // class
  628_021_283_683_842_752, // id
  13_795_232_291_291_665_398, // style
  15_722_393_318_163_439_657, // title
  315_497_910_460_527_221, // lang
  14_602_990_068_649_844_564, // dir
  8_999_596_768_310_594_794, // value
  48_647_938_514_502_632, // onclick
  13_325_619_438_517_705_282, // ondblclick
  416_083_448_746_125_191, // onmousedown
  3_001_231_464_796_748_894, // onmouseup
  2_966_091_320_067_286_745, // onmouseover
  8_767_684_291_872_348_978, // onmousemove
  15_381_059_881_359_187_517, // onmouseout
  7_978_597_548_511_006_054, // onkeypress
  8_084_358_405_739_883_515, // onkeydown
  7_285_022_664_070_919_770, // onkeyup
  1_290_860_685_949_344_712, // onfocus
  4_743_893_794_608_503_849, // onblur
  7_693_301_753_617_444_456, // onchange
]

/// Executable JavaScript MIME types that can be removed from script type attributes.
/// Matches html-minifier-next's `executableScriptsMimetypes`.
let executableScriptTypes: Set<String> = [
  "text/javascript",
  "text/x-javascript",
  "text/ecmascript",
  "text/x-ecmascript",
  "text/jscript",
  "application/javascript",
  "application/x-javascript",
  "application/ecmascript",
  "application/x-ecmascript",
  "module",
]

// MARK: - Default attribute values

/// Default attribute values that are redundant and can be removed.
/// General defaults (tagHash = 0) apply to any element.
/// Tag-specific defaults match only when both tag and attribute hashes match.
/// If an attribute's trimmed+lowered value matches the default, the attribute is removed.
struct DefaultAttr {
  let tagHash: UInt64
  let attrHash: UInt64
  let value: [UInt8]
}

let defaultAttrs: [DefaultAttr] = [
  // General defaults (tagHash = 0, match any tag)
  DefaultAttr(tagHash: 0, attrHash: 11_461_510_596_225_892_356, value: [0x6F, 0x6E]), // *:autocorrect="on"
  DefaultAttr(tagHash: 0, attrHash: 4_008_421_277_892_106_475, value: [0x61, 0x75, 0x74, 0x6F]), // *:fetchpriority="auto"
  DefaultAttr(tagHash: 0, attrHash: 2_634_281_930_376_072_727, value: [0x65, 0x61, 0x67, 0x65, 0x72]), // *:loading="eager"
  DefaultAttr(tagHash: 0, attrHash: 14_208_360_172_983_843_481, value: [0x74, 0x6F, 0x67, 0x67, 0x6C, 0x65]), // *:popovertargetaction="toggle"
  // Tag-specific defaults
  DefaultAttr(tagHash: 12_638_187_200_555_641_996, attrHash: 1_653_916_590_517_707_752, value: [0x5F, 0x73, 0x65, 0x6C, 0x66]), // a:target="_self"
  DefaultAttr(tagHash: 9_894_459_526_856_489_156, attrHash: 7_938_019_069_247_444_294, value: [0x72, 0x65, 0x63, 0x74]), // area:shape="rect"
  DefaultAttr(tagHash: 9_894_459_526_856_489_156, attrHash: 1_653_916_590_517_707_752, value: [0x5F, 0x73, 0x65, 0x6C, 0x66]), // area:target="_self"
  DefaultAttr(tagHash: 17_099_568_057_112_876_377, attrHash: 17_575_751_255_140_805_574, value: [0x61, 0x75, 0x74, 0x6F]), // audio:preload="auto"
  DefaultAttr(tagHash: 1_921_282_615_728_337_777, attrHash: 12_075_340_201_627_130_925, value: [0x73, 0x75, 0x62, 0x6D, 0x69, 0x74]), // button:type="submit"
  DefaultAttr(tagHash: 13_228_559_377_771_120_145, attrHash: 1_689_425_963_507_806_754, value: [0x31, 0x35, 0x30]), // canvas:height="150"
  DefaultAttr(tagHash: 13_228_559_377_771_120_145, attrHash: 15_842_200_671_275_313_599, value: [0x33, 0x30, 0x30]), // canvas:width="300"
  DefaultAttr(tagHash: 15_932_908_069_276_556_263, attrHash: 10_329_579_452_781_683_757, value: [0x6F, 0x6E]), // form:autocomplete="on"
  DefaultAttr(tagHash: 15_932_908_069_276_556_263, attrHash: 17_455_466_181_726_263_699, value: [0x61, 0x70, 0x70, 0x6C, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x2F, 0x78, 0x2D, 0x77, 0x77, 0x77, 0x2D, 0x66, 0x6F, 0x72, 0x6D, 0x2D, 0x75, 0x72, 0x6C, 0x65, 0x6E, 0x63, 0x6F, 0x64, 0x65, 0x64]), // form:enctype="application/x-www-form-urlencoded"
  DefaultAttr(tagHash: 15_932_908_069_276_556_263, attrHash: 2_525_399_976_365_011_888, value: [0x67, 0x65, 0x74]), // form:method="get"
  DefaultAttr(tagHash: 9_839_153_301_020_440_880, attrHash: 14_602_990_068_649_844_564, value: [0x6C, 0x74, 0x72]), // html:dir="ltr"
  DefaultAttr(tagHash: 3_142_648_431_874_569_604, attrHash: 16_121_265_193_124_312_056, value: [0x61, 0x75, 0x74, 0x6F]), // img:decoding="auto"
  DefaultAttr(tagHash: 2_214_555_572_463_777_371, attrHash: 12_075_340_201_627_130_925, value: [0x74, 0x65, 0x78, 0x74]), // input:type="text"
  DefaultAttr(tagHash: 13_784_282_253_595_985_929, attrHash: 12_912_867_724_530_986_883, value: [0x61, 0x6C, 0x6C]), // link:media="all"
  DefaultAttr(tagHash: 626_099_337_358_108_374, attrHash: 12_075_340_201_627_130_925, value: [0x31]), // ol:type="1"
  DefaultAttr(tagHash: 13_795_232_291_291_665_398, attrHash: 12_912_867_724_530_986_883, value: [0x61, 0x6C, 0x6C]), // style:media="all"
  DefaultAttr(tagHash: 16_973_714_742_696_204_443, attrHash: 13_514_075_383_012_487_877, value: [0x73, 0x6F, 0x66, 0x74]), // textarea:wrap="soft"
  DefaultAttr(tagHash: 16_052_404_288_867_766_460, attrHash: 17_265_840_922_154_185_283, value: [0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6C, 0x65, 0x73]), // track:kind="subtitles"
  DefaultAttr(tagHash: 14_081_220_367_743_959_884, attrHash: 17_575_751_255_140_805_574, value: [0x61, 0x75, 0x74, 0x6F]), // video:preload="auto"
]
